apiVersion: v1
kind: Service
metadata:
  name: nodejs-svc
  namespace: sajid
  labels:
    app: nodejs
spec:
  type: ClusterIP
  ports:
    - targetPort: 80
      port: 80
  selector:
    # app: nginx
    hat: red